    # Use an official Node.js runtime as the base image
    FROM node:18-alpine

    # Set the working directory inside the container
    WORKDIR /perf_test_project

    ARG DATABASE_URL="postgresql://db_user:password@db:5432/web_app_db"

    # Copy package.json and package-lock.json (or yarn.lock) first to leverage Docker caching
    COPY package*.json ./

    # Install dependencies
    RUN npm install

    # Needed for healthcheck for dependency
    RUN apk add --no-cache curl

    # Copy the rest of the application files
    COPY . .

    # Compile TypeScript to JavaScript
    RUN npm run build

    # Expose the application's port
    EXPOSE 3000

    # Command to start the application
    CMD ["npm", "start"]
